### ISSUE TITLE
Chroma Link and GameSense

### ISSUE THREAD

**Issue by Leogio360** [arxae/Razer-Gamesense#1]
Hi arxae, thanks for the work you did with this repo.  I see that it was tested only with Apex M800 keyboard. Do you think it's possibile to use your code to enable ChromaLink with Gamesense? Chroma Link overview [here](https://developer.razer.com/works-with-chroma/chroma-link-guide/) 
I will get soon the MSI MPG27CQ MONITOR, which support SteelSeries Gamesense, and I would like to use Overwatch effect on my monitor (change colour when health is low, and when ammo is low). 
I think that Chroma Link is the best way to achieve this. Let me know if you have some hints to do it.

**Comment by arxae** [comment]
Could work i think. This project current works by intercepting the calls to RzChromaSDK64.dll. If Chroma Link also uses this dll, then it should work. You will need to change the RazerHooks.cs file to intercept the correct calls though. And since I only have a keyboard for gamesense, i can't really tell you which one it is
